<style lang="postcss">
    .results_accordion_section {
        @apply px-64 py-16;
    }
    .results_accordion_section h2 {
        @apply text-3xl text-center mb-12 uppercase tracking-wide font-bold text-primary_red_dark;
    }
    h3 {
        @apply uppercase font-black text-primary_red text-xl;
    }
    table {
        @apply w-full mt-4 mb-12;
    }
    td {
        @apply border-b border-b-gray-border py-4 text-mobile-gray;
    }
</style>

<div id="results" class="results_accordion_section">
    <h2>Champions of the Accra Marathon</h2>

        <h3>Men's</h3>
        <table>
            <tbody>
                <tr>
                    <td>2016</td>
                    <td>Malik Yakubu</td>
                    <td>Ghana</td>
                    <td>2:22:46</td>
                </tr>
                <tr>
                    <td>2015</td>
                    <td>Alhassan Kassim Mohammed</td>
                    <td>Ghana</td>
                    <td>2:18:50</td>
                </tr>
                <tr>
                    <td>2014</td>
                    <td>Canceled</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2013</td>
                    <td>Alhaji Mohammed Kassim</td>
                    <td>Ghana</td>
                    <td>2:27:43</td>
                </tr>
                <tr>
                    <td>2012</td>
                    <td>Alex Kimeli</td>
                    <td>Kenya</td>
                    <td>2:26:00</td>
                </tr>
                <tr>
                    <td>2011</td>
                    <td>Akuka William</td>
                    <td>Ghana</td>
                    <td>2:26:02</td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td>Godwin Adukpo</td>
                    <td>Ghana</td>
                    <td>2:28:40</td>
                </tr>
                <tr>
                    <td>2009</td>
                    <td>Godwin Adukpo</td>
                    <td>Ghana</td>
                    <td>2:32:57</td>
                </tr>
                <tr>
                    <td>2008</td>
                    <td>Godwin Adukpo</td>
                    <td>Ghana</td>
                    <td>2:30:27</td>
                </tr>
                <tr>
                    <td>2007</td>
                    <td>David Zigah</td>
                    <td>Ghana</td>
                    <td>2:27:43</td>
                </tr>
                <tr>
                    <td>2006</td>
                    <td>David Zigah</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2005</td>
                    <td>Godwin Adukpo</td>
                    <td>Ghana</td>
                    <td>2:29:29</td>
                </tr>
                <tr>
                    <td>2004</td>
                    <td>Anthony Yin</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2003</td>
                    <td>David Zigah</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2002</td>
                    <td>David Zigah</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2001</td>
                    <td>David Zigah</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>2000</td>
                    <td>Stephen Manu</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1999</td>
                    <td>Richard Nifa</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1998</td>
                    <td>Alhaji Alhassan</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1997</td>
                    <td>Alhaji Alhassan</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1996</td>
                    <td>Stephen Manu</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1995</td>
                    <td>Stephen Manu</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1994</td>
                    <td>Hagack Gideon</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1993</td>
                    <td>Emmanuel Amo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1992</td>
                    <td>Fred Adongo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1991</td>
                    <td>Fred Adongo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1990</td>
                    <td>Emmanuel Amo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1989</td>
                    <td>Emmanuel Amo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1988</td>
                    <td>Fred Adongo</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
                <tr>
                    <td>1987</td>
                    <td>Alfred Amegashie</td>
                    <td>Ghana</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
      
        <h3>Womens</h3>
        <table>
            <tbody>
                <tr>
                    <td>2016</td>
                    <td>Elizabeth Azuure</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2015</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2014</td>
                    <td>Canceled</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2013</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2012</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2011</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2009</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2008</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2007</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2006</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2005</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2004</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2003</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2002</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2001</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2000</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1999</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1998</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1997</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1996</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1995</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1994</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1993</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1992</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1991</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1990</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1989</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1988</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1987</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
      

        <h3>Juniors</h3>
        <table>
            <tbody>
                <tr>
                    <td>2016</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2015</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2014</td>
                    <td>Canceled</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2013</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2012</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2011</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2009</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2008</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2007</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2006</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2005</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2004</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2003</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2002</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2001</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>2000</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1999</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1998</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1997</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1996</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1995</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1994</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1993</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1992</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1991</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1990</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1989</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1988</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>1987</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
      
</div>